### ISSUE TITLE
Pull Request/Issue inclusion criteria

### ISSUE THREAD

**Issue by kanadeCN** [shbwb/bwb#4]
## Important
We have already set up an issue(PR) template. If you want to leave comment on our project, please use the template. If the standard is not met, we will close your Issue (PR)

**Comment by qbsz** [comment]
Hey there.
Thanks for reporting this.
We will soon fix it :)

WIP

**Comment by qbsz** [comment]
Hey there.
Thanks for reporting this.
We will soon fix it :)

WIP
