### ISSUE TITLE
Demo of Library?

### ISSUE THREAD

**Issue by r-i-c-h** [shbwb/bwb#8]
## The main idea
You page is an explanation of syntax, but not an actual demonstration of the library.

**The Reason(s)**
I have no idea what the result will be of the library, so I am not likely to even try to use it.

**Comment by kanadeCN** [comment]
## reply

First of all, I'm sorry I didn't reply until so long. Thank you for your support for BWB project. If you see this message, please try to reply.

This is not a grammar introduction website, but a CSS library.

This is a bootstrap like project. It can be used to quickly build web pages.

However, the project is still in the initial development state, so the effect may not be ideal.

In the end of 2020, BWB will carry out large-scale modification and collation for the readme files of shbwb / BWB library. I will improve this project in the future.😃

<details>
<li>
This message is answered by a real person!🧑‍💻
</li>
</details>

**Comment by kanadeCN** [comment]
I will keep this issue open until your problem is solved.

Have  a nice day ;)

**Comment by qbsz** [comment]
Could you tell me how you know about this project? Thanks.

**Comment by kanadeCN** [comment]
I'm curious about how you learned about BWB? You can share it with me

**Comment by r-i-c-h** [comment]
Here is my answer/ your bug - *THIS* Website: [https://bwb-docs.js.org/](https://bwb-docs.js.org/)  is *NOT* the URL I went to that is in your sidebar: [https://bwb.js.org/](https://bwb.js.org/)
